import React from 'react';
import ProjectCard from './ProjectCard';

const Projects: React.FC = () => {
  const projects = [
    {
      title: "AI-Powered Maternal Health Risk Prediction",
      description: "Developed and trained a custom machine learning model to predict maternal health risks, achieving 94% accuracy and providing personalized care recommendations.",
      // --- ACTION NEEDED: Replace this with your REAL project image URL ---
      image: "/image/maternal-health-preview.png",
      technologies: ["Python", "TensorFlow", "Flask", "Next.js", "Firebase"],
      // Your live URL is correctly placed here.
      liveUrl: "https://maternal-frontend.vercel.app",
      // We set this to "#" since you want to keep the code private. The ProjectCard will hide the button.
      githubUrl: "#"
    },
    {
      title: "Annex | Knowledge Marketplace",
      description: "Architecting a full-stack e-learning platform for teachers to sell lessons and for students to find tutors. (Currently in Development)",
      // --- ACTION NEEDED: Replace this with your REAL project image URL ---
      image: "/image/annex.png",
      technologies: ["Next.js", "NestJS", "PostgreSQL", "Tailwind CSS"],
      // Set to "#" because it's not ready for a public demo yet.
      liveUrl: "#",
      githubUrl: "#"
    },
{
    title: "UmoyoCard | AI Digital Health Passport Scanner",
    // 👇 This is the new, professional description 👇
    description: "A mobile application developed in Flutter that digitizes paper health passports. It leverages the Gemini AI model for advanced OCR to accurately extract handwritten medical text, which is then securely stored in a Firebase database. The app also features predictive analytics and data sharing capabilities for hospital systems.",
    image: "/image/health-passport-preview.jpg",
    technologies: ["Flutter", "Firebase", "Gemini API"],
    liveUrl: "#",
    githubUrl: "#"
  }
    // // --- CHANGE 1: Moved this project to the top ---
    // {
    //   title: "AI-Powered Analytics",
    //   description: "Machine learning dashboard for data visualization and predictive analytics, leveraging TensorFlow models to provide real-time insights from complex datasets.", // Minor description enhancement
    //   image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219086456_cdd135ea.webp",
    //   technologies: ["Python", "TensorFlow", "D3.js", "Flask"],
    //   liveUrl: "#https://maternal-frontend.vercel.app",
    //   githubUrl: "#"
    // },
    // // --- CHANGE 2: Moved this project to second place and enhanced it ---
    // {
    //   title: "Cryptocurrency Tracker",
    //   // --- Explicitly mention the AI technique used ---
    //   description: "Real-time crypto portfolio tracker featuring price alerts and trading recommendations generated by a PyTorch-based LSTM model trained on historical market data.",
    //   image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219092471_5cb65fae.webp",
    //   // --- Add the AI technology to the list ---
    //   technologies: ["React", "Redux", "WebSocket", "PyTorch"],
    //   liveUrl: "#",
    //   githubUrl: "#"
    // },
    // // --- CHANGE 3: Enhanced this project description to include an AI feature ---
    // {
    //   title: "E-Commerce Platform",
    //   description: "Full-stack solution with React and Node.js, featuring an AI-powered recommendation engine built with Scikit-learn to personalize user shopping experiences.",
    //   image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219082548_75ef00cf.webp",
    //   // --- Add the AI technology to the list ---
    //   technologies: ["React", "Node.js", "MongoDB", "Scikit-learn"],
    //   liveUrl: "#",
    //   githubUrl: "#"
    // },
    // {
    //   title: "Mobile Banking App",
    //   description: "Secure mobile banking application with biometric authentication, transaction history, and budget tracking features.",
    //   image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219088529_408d05c8.webp",
    //   technologies: ["React Native", "Express", "PostgreSQL"],
    //   liveUrl: "#",
    //   githubUrl: "#"
    // },
    // {
    //   title: "Social Media Dashboard",
    //   description: "Comprehensive social media management platform with scheduling, analytics, and multi-platform posting capabilities.",
    //   image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219090448_57a69fd4.webp",
    //   technologies: ["Angular", "TypeScript", "GraphQL"],
    //   liveUrl: "#",
    //   githubUrl: "#"
    // },
    //  {
    //   title: "Task Management App",
    //   description: "Collaborative project management tool with real-time updates, drag-and-drop functionality, and team collaboration features.",
    //   image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219084438_435d8574.webp",
    //   technologies: ["Vue.js", "Firebase", "Tailwind CSS"],
    //   liveUrl: "#",
    //   githubUrl: "#"
    // },
  ];

  return (
    <section id="projects" className="py-20 bg-gray-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Featured <span className="text-cyan-400">Projects</span>
          </h2>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Explore my latest work showcasing innovative solutions and cutting-edge technologies
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projects.map((project, index) => (
            <ProjectCard key={index} {...project} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;

// import React from 'react';
// import ProjectCard from './ProjectCard';

// const Projects: React.FC = () => {
//   const projects = [
//     {
//       title: "E-Commerce Platform",
//       description: "Full-stack e-commerce solution with React, Node.js, and MongoDB. Features include user authentication, payment processing, and admin dashboard.",
//       image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219082548_75ef00cf.webp",
//       technologies: ["React", "Node.js", "MongoDB", "Stripe"],
//       liveUrl: "#",
//       githubUrl: "#"
//     },
//     {
//       title: "Task Management App",
//       description: "Collaborative project management tool with real-time updates, drag-and-drop functionality, and team collaboration features.",
//       image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219084438_435d8574.webp",
//       technologies: ["Vue.js", "Firebase", "Tailwind CSS"],
//       liveUrl: "#",
//       githubUrl: "#"
//     },
//     {
//       title: "AI-Powered Analytics",
//       description: "Machine learning dashboard for data visualization and predictive analytics with interactive charts and real-time insights.",
//       image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219086456_cdd135ea.webp",
//       technologies: ["Python", "TensorFlow", "D3.js", "Flask"],
//       liveUrl: "#",
//       githubUrl: "#"
//     },
//     {
//       title: "Mobile Banking App",
//       description: "Secure mobile banking application with biometric authentication, transaction history, and budget tracking features.",
//       image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219088529_408d05c8.webp",
//       technologies: ["React Native", "Express", "PostgreSQL"],
//       liveUrl: "#",
//       githubUrl: "#"
//     },
//     {
//       title: "Social Media Dashboard",
//       description: "Comprehensive social media management platform with scheduling, analytics, and multi-platform posting capabilities.",
//       image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219090448_57a69fd4.webp",
//       technologies: ["Angular", "TypeScript", "GraphQL"],
//       liveUrl: "#",
//       githubUrl: "#"
//     },
//     {
//       title: "Cryptocurrency Tracker",
//       description: "Real-time cryptocurrency portfolio tracker with price alerts, market analysis, and trading recommendations.",
//       image: "https://d64gsuwffb70l.cloudfront.net/68adc6976e048bfc8e4946f2_1756219092471_5cb65fae.webp",
//       technologies: ["React", "Redux", "WebSocket", "Chart.js"],
//       liveUrl: "#",
//       githubUrl: "#"
//     }
//   ];

//   return (
//     <section id="projects" className="py-20 bg-gray-900">
//       <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
//         <div className="text-center mb-16">
//           <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
//             Featured <span className="text-cyan-400">Projects</span>
//           </h2>
//           <p className="text-xl text-gray-400 max-w-2xl mx-auto">
//             Explore my latest work showcasing innovative solutions and cutting-edge technologies
//           </p>
//         </div>
        
//         <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
//           {projects.map((project, index) => (
//             <ProjectCard key={index} {...project} />
//           ))}
//         </div>
//       </div>
//     </section>
//   );
// };

// export default Projects;